trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureStaticWebApp@0
  displayName: "Deploy SWA to LEC"
  inputs:
    azure_static_web_apps_api_token: $(DP_LEC)

- task: AzureStaticWebApp@0
  displayName: "Deploy SWA to TTA"
  inputs:
    azure_static_web_apps_api_token: $(DP_TTA)

- task: AzureStaticWebApp@0
  displayName: "Deploy SWA to TTA Internal"
  inputs:
    azure_static_web_apps_api_token: $(DP_TTA_INT)
