trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureCLI@2
  displayName: "Get SWA Deployment Key for LEC"
  inputs:
    azureSubscription: 'leading-edge-computers'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      lecapikey=$(az staticwebapp secrets list --name swa-lec-cipp --query "properties.apiKey" | tr -d '"')
      if [ $lecapikey ]; then echo "API Key Found"; fi
      echo "##vso[task.setvariable variable=deploymentTokenLEC]$lecapikey"

- task: AzureCLI@2
  displayName: "Get SWA Deployment Key for TTA"
  inputs:
    azureSubscription: 'azure-sub-partner-network'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      apikey=$(az staticwebapp secrets list --name swa-tta-cipp --query "properties.apiKey" | tr -d '"')
      if [ $apikey ]; then echo "API Key Found"; fi
      echo "##vso[task.setvariable variable=deploymentTokenTTA]$apikey"

- task: AzureStaticWebApp@0
  displayName: "Deploy CIPP SWA to LEC"
  retryCountOnTaskFailure: 2
  inputs:
    app_location: '/'
    azure_static_web_apps_api_token: '$(deploymentTokenLEC)'

- task: AzureStaticWebApp@0
  displayName: "Deploy CIPP SWA to TTA"
  retryCountOnTaskFailure: 2
  inputs:
    app_location: '/'
    azure_static_web_apps_api_token: '$(deploymentTokenTTA)'
